development:
  stripe_publishable_key: pk_test_51HhP89EdG4r8FMZlJ3XfyfMRMjonqqRR9RrNwWTSotfHXimwerQDuDZrJYzuHZrf4LT7KTP3BnpjGq6YhcT9aEnj0031YQsWl6
  stripe_secret_key: sk_test_51HhP89EdG4r8FMZlpqZdDLo7AJdtBwVztguG4XKNUeJVDrbEPWnbGQx1dBvSkRAt9Fa4vHdKQjTwGGEnc8PzBpaR00g5blowkX

  production:
  stripe_publishable_key: ENV['stripe_publishable_key']
  stripe_secret_key: ENV['stripe_publishable_key']